name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Libraries
      run: |
        sudo apt update
        sudo apt install -y libasound2-dev
        sudo apt-get install libudev-dev
    - name: Build
      run: cargo build --verbose
